before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - export CCACHE_DIR=/dev/shm/my-ccache-in-memory
  - export CCACHE_NOCOMPRESS=1
  - df -h /dev/shm
  - echo "Acquire::http::Proxy \"http://192.168.1.10:3142\";" > /etc/apt/apt.conf.d/00aptproxy
  - apt-get update
  - apt-get dist-upgrade -yq
  - apt-get install -yq ccache device-tree-compiler gcc-arm-linux-gnueabihf libgnutls28-dev python3-cryptography python3-dev python3-jsonschema python3-pycryptodome python3-pyelftools python3-setuptools python3-yaml swig uuid-dev yamllint
  - touch .gitlab-runner
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"
  - git config --global advice.detachedHead false

build-debian-14-arm64:
  image: robertcnelson/beagle-devscripts-kernel-debian-14-arm64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-debian-14-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - tar --zstd -xf ccache.tar.zst -C / || true
    - df -h /dev/shm
    - ccache -M 1G
    - ccache -sv
    - ccache --recompress=uncompressed
    - ccache -z
    - ./build_u-boot.sh
    - ccache -sv
    - df -h /dev/shm
    - tar --use-compress-program='zstd -9' -cf ccache.tar.zst /dev/shm/my-ccache-in-memory

build-debian-13-arm64:
  image: robertcnelson/beagle-devscripts-kernel-debian-13-arm64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-debian-13-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - tar --zstd -xf ccache.tar.zst -C / || true
    - df -h /dev/shm
    - ccache -M 1G
    - ccache -sv
    - ccache --recompress=uncompressed
    - ccache -z
    - ./build_u-boot.sh
    - ccache -sv
    - df -h /dev/shm
    - tar --use-compress-program='zstd -9' -cf ccache.tar.zst /dev/shm/my-ccache-in-memory

pages:
  image: robertcnelson/beagle-devscripts-kernel-debian-12-arm64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  cache:
    key: "$CI_PROJECT_NAME-debian-12-arm64"
    paths:
      - ccache.tar.zst
  tags:
    - docker-aarch64-rpi4-ci
  stage: build
  script:
    - tar --zstd -xf ccache.tar.zst -C / || true
    - df -h /dev/shm
    - ccache -M 1G
    - ccache -sv
    - ccache --recompress=uncompressed
    - ccache -z
    - ./build_u-boot.sh
    - ccache -sv
    - df -h /dev/shm
    - tar --use-compress-program='zstd -9' -cf ccache.tar.zst /dev/shm/my-ccache-in-memory
    - apindex public
  artifacts:
    when: on_success
    paths:
      - public
  only:
  - main
